import { CollectionConfig } from "payload/types";

const Blogs:CollectionConfig = {
    slug:'blogs',
    fields:[
        {
            type:"upload",
            name:"Image",
            relationTo:"media",
            required:true
        },
        {
            type:"textarea",
            name:"Heading",
            required:true
        },
        {
            type:"textarea",
            name:"SubHeading1",
            required:false
        },
        {
            type:"textarea",
            name:"SubHeading2",
            required:false
        },
        {
            type:"textarea",
            name:"SubHeading3",
            required:false
        },
        {
            type:"textarea",
            name:"SubHeading4",
            required:false
        },
        {
            type:"textarea",
            name:"MainDescription",
            required:true
        },
        {
            type:"textarea",
            name:"MainDescription1",
            required:false
        },
        {
            type:"textarea",
            name:"MainDescription2",
            required:false
        },
        {
            type:"textarea",
            name:"MainDescription3",
            required:false
        },
        {
            type:"textarea",
            name:"Sud1Description1",
            required:false
        },
        {
            type:"textarea",
            name:"Sud1Description2",
            required:false
        },
        {
            type:"textarea",
            name:"Sud1Description3",
            required:false
        },
        {
            type:"textarea",
            name:"Sud2Description1",
            required:false
        },
        {
            type:"textarea",
            name:"Sud2Description2",
            required:false
        },
        {
            type:"textarea",
            name:"Sud2Description3",
            required:false
        },
        {
            type:"textarea",
            name:"Sud3Description1",
            required:false
        },
        {
            type:"textarea",
            name:"Sud3Description2",
            required:false
        },
        {
            type:"textarea",
            name:"Sud3Description3",
            required:false
        },
        {
            type:"textarea",
            name:"Sud4Description1",
            required:false
        },
        {
            type:"textarea",
            name:"Sud4Description2",
            required:false
        },
        {
            type:"textarea",
            name:"Sud4Description3",
            required:false
        },
     

    ]
}

export default Blogs;